createNamespace: true
namespace: my-app

deployment:
  replicaCount: 1
  image: my-app-image
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: my-app-service
  type: ClusterIP
  port: 80

resources: 
      limits:
        cpu: "1500m"
        memory: "6Gi"
      requests:
        cpu: "1000m"
        memory: "4Gi"


hpa:
  minReplicas: 1
  maxReplicas: 3

nodeSelector: {}

tolerations: []

affinity: {}
