apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: my-app-network-policy
  namespace: my-app 
spec:
  podSelector:
    matchLabels:
      app: my-app 
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: trusted 
    - namespaceSelector: {} 
  egress:
  - to:
    - namespaceSelector: {} 
